version: '3.8'

services:
  nutriquest-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  nutriquest-dev:
    build: .
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
