// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual API key
    appId: '1:123456789012:web:abcdefghijklmnop', // Replace with your actual app ID
    messagingSenderId: '123456789012', // Replace with your actual sender ID
    projectId: 'nutriquest-app', // Replace with your actual project ID
    authDomain: 'nutriquest-app.firebaseapp.com', // Replace with your actual auth domain
    storageBucket: 'nutriquest-app.appspot.com', // Replace with your actual storage bucket
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual API key
    appId: '1:123456789012:android:abcdefghijklmnop', // Replace with your actual app ID
    messagingSenderId: '123456789012', // Replace with your actual sender ID
    projectId: 'nutriquest-app', // Replace with your actual project ID
    storageBucket: 'nutriquest-app.appspot.com', // Replace with your actual storage bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual API key
    appId: '1:123456789012:ios:abcdefghijklmnop', // Replace with your actual app ID
    messagingSenderId: '123456789012', // Replace with your actual sender ID
    projectId: 'nutriquest-app', // Replace with your actual project ID
    storageBucket: 'nutriquest-app.appspot.com', // Replace with your actual storage bucket
    iosBundleId: 'com.nutriquest.app', // Replace with your actual bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual API key
    appId: '1:123456789012:ios:abcdefghijklmnop', // Replace with your actual app ID
    messagingSenderId: '123456789012', // Replace with your actual sender ID
    projectId: 'nutriquest-app', // Replace with your actual project ID
    storageBucket: 'nutriquest-app.appspot.com', // Replace with your actual storage bucket
    iosBundleId: 'com.nutriquest.app', // Replace with your actual bundle ID
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // Replace with your actual API key
    appId: '1:123456789012:web:abcdefghijklmnop', // Replace with your actual app ID
    messagingSenderId: '123456789012', // Replace with your actual sender ID
    projectId: 'nutriquest-app', // Replace with your actual project ID
    authDomain: 'nutriquest-app.firebaseapp.com', // Replace with your actual auth domain
    storageBucket: 'nutriquest-app.appspot.com', // Replace with your actual storage bucket
  );
}
